#!/ bin / bash
#Author : baoxian zhang[baoxianzhang] < baoxianzhit @gmail.com >
#
#This file include the flags which softwares you need
FLAG_APT_GET_UPDATE = 0 FLAG_APT_GET_SOFTWARE_INSTALL = 0 FLAG_GIT_INSTALL =
    0 FLAG_GIT_EMAIL_NAME_CONFIG = 0 FLAG_CMAKE_INSTALL = 0 FLAG_ZSH_INSTALL =
        0 FLAG_AUTOJUMP_INSTALL = 0 FLAG_CTAGS_INSTALL = 0 FLAG_GTAGS_INSTALL =
            0 FLAG_VIM_INSTALL = 0 FLAG_SPF13VIM_INSTALL =
                0 FLAG_MYVIM_LOCAL_SETTINGS_CONFIG = 0 FLAG_SOFTLINK_ZSHRC_INSTALL =
                    0 FLAG_SOFTLINK_TMUX_INSTALL = 0 FLAG_FZF_INSTALL =
                        0 FLAG_EMACS_INSTALL = 0 FLAG_SPACEMACS_INSTALL =
                            0 FLAG_SOFTLINK_SPACEMACS_CONFIG =
                                0 FLAG_ZEAL_FOR_SPACEMACE_INSTALL =
                                    0 FLAG_DASH_ZEAL_DOCSETS_FOR_SPACEMACE_INSTALL =
                                        0 FLAG_PDFTOOL_FOR_SPACEMACE_INSTALL =
                                            0 FLAG_SYSTEM_INDICATOR_INSTALL =
                                                0 FLAG_HAROOPAD_FOR_MARKDOWN_INSTALL =
                                                    0 FLAG_RIPGREP_INSTALL = 0

    ########################################The
        following not test######################## #FLAG_ARM_NONE_EABI_GCC_4dot9dot3_INSTALL =
            0 FLAG_ESPTOOL_INSTALL = 0 FLAG_STLINK_INSTALL =
                0 FLAG_RUST_INSTALL = 0 FLAG_GO_FOR_IT_INSTALL =
                    0 FLAG_THEFUCK_INSTALL =
                        0 FLAG_MERCURY_MW150US_WIRELESS_INSTALL =
                            0 FLAG_LATEX_INSTALL =
                                0 FLAG_SCEL2PYIM_FOR_SPACEMACE_INSTALL =
                                    0 FLAG_WAKATIME_FOR_SPACEMACE_INSTALL =
                                        0 FLAG_GOLDENDICT_INSTALL = 0

    FLAG_PANDOC_FOR_SPACEMACE_INSTALL = 0 FLAG_GOOGLE_HOSTS_INSTALL =
        0 FLAG_FLAT_THEMES_ICONS_INSTALL = 0 FLAG_SHADOWSOCKS_INSTALL =
            0 FLAG_LAUNCHERFODERS_INSTALL = 0

    FLAG_VIRTUALBOX_INSTALL = 0 FLAG_VIRTUALBOX_WIN7_INSTALL =
        0 FLAG_VAGRANT_INSTALL = 0 FLAG_VAGRANT_TRUSTY64_INSTALL =
            0 FLAG_XTENSA_INSTALL = 0 FLAG_SKYPE_INSTALL = 0

    FLAG_SECURECRT7dot3_INSTALL = 0 FLAG_SOFTLINK_GIT_TEMPLATES_INSTALL = 0
#FLAG_MERCURY_MW150US_WIRELESS_INSTALL = 0
#FLAG_EMACS24dot5_INSTALL = 0
#FLAG_SOFTLINK_EMACS_INSTALL = 0
#FLAG_GOOGLEPINYIN_INSTALL = 0
#FLAG_VIRTUALBOX_INSTALL = 0
#FLAG_VIRTUALBOX_WIN7_INSTALL = 0
#FLAG_VAGRANT_INSTALL = 0
#FLAG_VAGRANT_TRUSTY64_INSTALL = 0
#FLAG_XTENSA_INSTALL = 0
#FLAG_GOOGLE_HOSTS_INSTALL = 0
#FLAG_SECURECRT7dot3_INSTALL = 0
#FLAG_FLAT_THEMES_ICONS_INSTALL = 0
#FLAG_SHADOWSOCKS_INSTALL = 0
