#!/usr/bin/env bash

# Validate commit log
commit_regex='^Merge.+|(feat|fix|docs|perf|style|refactor|test|build|chore|revert|types)(\(.+\))?: .{1,50}'

if ! grep -iqE "$commit_regex" "$1"; then
    echo
    echo "  Error: proper commit message format is required for automated changelog generation."
    echo
    exit 1
fi
